import type { RestorationContent } from "@/components/restoration-page";

const related = [
  { title: "Dentures", description: "A modern removable full or partial tooth-replacement option.", href: "/services/dentures" },
  { title: "Snap-in overdentures", description: "A removable denture that attaches to implants for added retention.", href: "/services/implant-supported-overdentures" },
  { title: "All-on-4 / All-on-X", description: "A fixed full-arch implant option for suitable candidates.", href: "/services/all-on-4-all-on-x" },
];

export const RESTORATION_PAGES: Record<string, RestorationContent> = {
  "dental-implants": {
    eyebrow: "Tooth replacement options", title: "Dental Implants", description: "A carefully planned way to replace one or more missing teeth with a restoration supported by an implant.", image: "/dental-implants-hero.png", imageAlt: "Dental implant planning model in a modern consultation room",
    overviewTitle: "A foundation for a new tooth", overview: ["A dental implant is placed in the jaw to support a replacement tooth or teeth. It may support an individual crown, a bridge, a removable overdenture, or a fixed full-arch restoration.", "We begin with your oral health, goals, and anatomy. From there, we can explain whether an implant-based option makes sense for you and what the treatment stages may look like."],
    benefits: [{ title: "Individualised restoration", description: "Implants can support a range of tooth-replacement designs, depending on your needs." }, { title: "Thoughtful planning", description: "The implant, restoration, bite, and surrounding teeth are considered together." }, { title: "Long-term care", description: "Like natural teeth, implant restorations benefit from regular hygiene and professional care." }],
    considerations: [{ title: "Healing time", description: "The treatment sequence and healing needs are specific to your case." }, { title: "Suitability", description: "Bone, gums, oral health, and medical history all inform planning." }, { title: "Maintenance", description: "Your restoration and supporting tissues need daily care and follow-up." }],
    steps: [{ title: "Consultation", description: "We review your goals and oral health." }, { title: "Assessment and planning", description: "3D CBCT imaging may be used when clinically appropriate." }, { title: "Implant treatment", description: "Placement and healing are planned around your individual situation." }, { title: "Final restoration", description: "We fit and review the restoration and its care routine." }],
    faqs: [{ question: "Can implants replace more than one tooth?", answer: "Yes. Depending on your needs, implants can support an individual crown, a bridge, a removable overdenture, or a fixed full-arch restoration." }, { question: "Will an implant be right for me?", answer: "Suitability is determined after a complete assessment of your oral health, anatomy, and treatment goals." }, { question: "How long does treatment take?", answer: "The timing depends on your plan, healing, and whether preparatory care is needed. We will explain the expected sequence for you." }],
    related, technology: { title: "CBCT 3D imaging", description: "When appropriate, 3D imaging can support detailed assessment and implant treatment planning.", href: "/technology#cbct" },
  },
  dentures: {
    eyebrow: "Tooth replacement options", title: "Dentures", description: "Modern full and partial dentures can restore the appearance and everyday function of your smile with a removable option tailored to you.", image: "/dentures-hero.png", imageAlt: "A refined denture model in a modern dental consultation setting",
    overviewTitle: "A removable option with a thoughtful fit", overview: ["Dentures are custom-made removable teeth that can replace a full arch or fill spaces left by several missing teeth. Full dentures replace a complete arch, while partial dentures work around the healthy teeth you still have.", "We take time to plan the fit, bite, and appearance, then explain how conventional dentures, implant-supported overdentures, or a fixed full-arch option may fit your goals."],
    benefits: [{ title: "Replace several or all teeth", description: "A practical removable option when several teeth or a full arch need replacement." }, { title: "Custom appearance", description: "The shape, shade, and fit are planned for your smile." }, { title: "Flexible pathway", description: "For some people, dentures may be a starting point before considering implants later." }],
    considerations: [{ title: "Adjustment period", description: "Speaking and eating with new dentures can take time to feel familiar." }, { title: "Changing fit", description: "Mouth changes can make reviews, relines, or adjustments important." }, { title: "Support options", description: "If movement is a concern, we can discuss implant-supported overdentures." }],
    steps: [{ title: "Consultation", description: "We review your oral health and replacement options." }, { title: "Planning", description: "We collect the records needed to plan fit, bite, and appearance." }, { title: "Try-in", description: "We check important details before the final denture is made." }, { title: "Follow-up", description: "We review care and make adjustments when needed." }],
    faqs: [{ question: "Can I have a partial denture if I still have teeth?", answer: "Often, yes. We will assess the condition of the teeth you still have and the best way to replace the missing ones." }, { question: "What if my denture feels loose?", answer: "Let us know. We can assess the fit and discuss an adjustment, reline, replacement, or implant support." }, { question: "How do I care for dentures?", answer: "We will show you a cleaning routine for the denture, gums, and any remaining teeth." }], related,
  },
  "implant-supported-overdentures": {
    eyebrow: "Tooth replacement options", title: "Implant-Supported Overdentures", description: "A removable denture that attaches to implants for a more secure, snap-in option than a conventional denture alone.", image: "/implant-supported-overdentures-hero.png", imageAlt: "A denture model with implant attachment components in a dental planning setting",
    overviewTitle: "Removable, with added support", overview: ["An implant-supported overdenture is a removable denture designed to connect to dental implants. You can take it out for cleaning, while the implants help provide retention and support during daily use.", "This can be a useful option when a conventional denture moves more than you would like. The number and placement of implants are planned around your individual needs."],
    benefits: [{ title: "More retention", description: "Implant attachments can reduce unwanted movement compared with a conventional denture alone." }, { title: "Removable for cleaning", description: "You remove the overdenture to clean it and care for the attachments." }, { title: "A middle ground", description: "It balances implant support with the familiarity of a removable denture." }],
    considerations: [{ title: "Implant suitability", description: "A consultation determines whether implant support is appropriate." }, { title: "Healing and visits", description: "Treatment stages and healing depend on your specific situation." }, { title: "Maintenance", description: "Attachments and dentures need regular cleaning and professional reviews." }],
    steps: [{ title: "Consultation", description: "We discuss what you want to improve about your current denture." }, { title: "Assessment", description: "We assess your mouth, bone, and gums; 3D imaging may be considered when appropriate." }, { title: "Implant treatment", description: "If implants are suitable, the treatment and healing stages are planned." }, { title: "Attachment and care", description: "We fit the overdenture and review its care and follow-up." }],
    faqs: [{ question: "Are overdentures the same as All-on-4?", answer: "No. An overdenture is removable by you. An All-on-4 / All-on-X restoration is fixed and removed only by a dental professional." }, { question: "Can my existing denture be used?", answer: "Sometimes, but it needs to be assessed for fit, condition, and design first." }, { question: "How many implants are needed?", answer: "That depends on your anatomy, denture design, and goals." }], related, technology: { title: "3D planning when appropriate", description: "CBCT imaging can support a detailed assessment and treatment plan when clinical needs call for it.", href: "/technology#cbct" },
  },
  "all-on-4-all-on-x": {
    eyebrow: "Full-arch tooth replacement", title: "All-on-4 / All-on-X", description: "A fixed full-arch tooth-replacement option supported by implants and planned around your health, goals, and anatomy.", image: "/all-on-x-hero.png", imageAlt: "A full-arch prosthetic model and 3D planning screen in a modern dental setting",
    overviewTitle: "A fixed full-arch option", overview: ["All-on-4 / All-on-X describes a full-arch restoration fixed to dental implants. It is designed for people replacing an entire upper or lower arch of teeth and is removed only by a dental professional for service when needed.", "The number, position, and type of implants are individual to you. We start with a detailed assessment so we can explain whether a fixed full-arch restoration, an overdenture, or another approach is the better fit."],
    benefits: [{ title: "Fixed day to day", description: "A fixed restoration stays in place during normal daily activities." }, { title: "One coordinated plan", description: "Planning considers your teeth, bite, gums, bone support, and goals." }, { title: "A restorative pathway", description: "For suitable candidates, it may be an alternative to a removable full denture." }],
    considerations: [{ title: "Detailed assessment", description: "Suitability depends on your health, oral health, anatomy, and goals." }, { title: "Treatment stages", description: "Appointments, healing, temporary options, and final timing are case-specific." }, { title: "Long-term care", description: "Fixed restorations still need daily hygiene and professional maintenance." }],
    steps: [{ title: "Consultation", description: "We review what you want from treatment and your health history." }, { title: "3D assessment", description: "CBCT imaging may be used when appropriate to support planning." }, { title: "Treatment sequence", description: "We map the stages of care around your needs." }, { title: "Final restoration", description: "We fit the restoration and review ongoing care." }],
    faqs: [{ question: "What does All-on-X mean?", answer: "It is a broad term for a fixed full-arch restoration supported by implants. The number of implants and design are decided after assessment." }, { question: "Is All-on-4 removable?", answer: "A fixed All-on-4 / All-on-X restoration is not removed at home. An overdenture is the removable implant-supported option." }, { question: "Will I receive teeth on the same day?", answer: "Timing and temporary-to-final options depend on clinical findings and your individual plan." }], related, technology: { title: "CBCT-guided assessment", description: "When clinically appropriate, CBCT can help us visualise anatomy in three dimensions for detailed planning.", href: "/technology#cbct" },
  },
};
